# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Text-CSV-Simple
version:      0.10
version_from: lib/Text/CSV/Simple.pm
installdirs:  site
requires:
    File::Slurp:                   0
    Text::CSV_XS:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
